### PR TITLE
[WIP] Try to convert build to Win

### PR DESCRIPTION
**Pull request by forki**
Current status: I/O error. Ideas?

image

### CODE REVIEW

**Comment by kjnilsson** [comment]
Hi - I tried it and it seems like it isn't expanding the `*.erl` wildcard and tries to compile it as  single file. not sure if that is and `erlc` issue or what. you could work around by listing src/*.erl and pipe each into `erlc` perhaps.

Thanks for looking at this btw :)

**Comment by kjnilsson** [comment]
This may be relevant: http://erlang.org/pipermail/erlang-questions/2011-January/056066.html

**Comment by forki** [comment]
ok that works.
Next issue: I have no idea what to do  with the fezc now!?

**Comment by forki** [comment]
creating a cmd? like in @eb188b9 ?

**Comment by kjnilsson** [comment]
fezc is a mess and I just realised it is also buggy. :)

What is needed is basically a script that takes a bunch of files as arguments, `dotnet run src/fez/fez.fproj <args>` to generate the `.core` files then `erlc` all the `.core` files into the same directory. What the current script doesn't take into account is the fact that an `.fs` file could generate multiple `.core` files (one for the main module then one for each nested module).

**Comment by forki** [comment]
how about letting this be done directly by the dotnet project?
It could automate erlc right?

**Comment by kjnilsson** [comment]
Ideally I'd like to keep `fez` as and fsharp to core erlang compiler as I suspect that would play nicer with other erlang build tools but perhaps we could have it as an option?

Alternatively maybe fez should output a list of the .core files it generates then we could just pipe that into `erlc`

**Comment by forki** [comment]
yes fine. also it should not output the core file on stdout.  what a waste of runtime ;-)

**Comment by kjnilsson** [comment]
it may print the fsharp ast atm if I forgot to comment that line out :)

I meant output the paths to the .core files rather than the file contents. it should definitely write that as current is done.

**Comment by forki** [comment]
cool. I'd then rebase on your changes ;-)

**Comment by forki** [comment]
ok my cmd is now building the basics.fs just fine to beam. How can I run it?

**Comment by kjnilsson** [comment]
Run-tests.sh uses the output of basic.fs. Alternatively you could do `erl -pa ebin test` to open a shell with the appropriate search paths.

**Comment by forki** [comment]
image

wow!

**Comment by kjnilsson** [comment]
I know right! ;)

**Comment by forki** [comment]
Ok removed the AST printing

**Comment by forki** [comment]
printing OUTFILEs instead

**Comment by forki** [comment]
ok my cmd file is captering the files and send it to erlc. That's nice!

**Comment by forki** [comment]
erl

**Comment by Lleutch** [comment]
That's so sweet 💯 !!!

**Comment by kjnilsson** [comment]
Fantastic. Ready to merge?

**Comment by forki** [comment]
@kjnilsson you would need to patch the unix side I'm afraid

**Comment by forki** [comment]
but apart from that yes.

**Comment by kjnilsson** [comment]
That's fine. It might still work.

**Pull request merged**
